title: Researcher
url: "https://kalenaholeman.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: 
footer_text: "Kalena Holeman"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "Kalena Holeman CV.pdf"
 - name: "Contact"
   link: "contact"
